---
---

<link rel="stylesheet" href="styles.css" type="text/css">

## About Young Demographers
We are a group of young (at least in mind) demography enthusiasts, mostly PhD students from the Charles University. Besides working hard on our dissertations and research, we like to meet new people who are crazy about tables and figures, but who also like fun. We want to keep demography **young** and **live**. Our main activity is organizing the international conference for young demographers from all around the world. 

## About young demographers
Although we have semi-official "club" of Young Demographers at the Charles University, we know that there are plenty more **young demographers** out there. They are smart and open-minded people who love science, demography, population studies, research and discovering new things. Besides being serious and rigorous in their papers and other official work, they do not hesitate to join us and have as much fun with demography as possible. 

**They are you!**

If you feel like being one of us, please send us a message, come to our conference or just say "Hi!" if you meet any of us somewhere. We will be looking forward do meeting you in person.
