---
---

<link rel="stylesheet" href="styles.css" type="text/css">

### Conference of Young Demographers
The annual international **Conference of Young Demographers** is held at the [Faculty of Science, Charles University](https://www.natur.cuni.cz/eng) traditionally in the first half of February. We welcome submissions from all fields of demography, as well as all related areas of population studies. We aim to create a relaxed and welcoming environment where especially early career researchers can share their work in progress and thoughts with their peers.

We understand the pressure they might feel at big international conferences full of well-established professors (we feel it too). So we try to provide an opportunity to try to present without worries, often for the first time in their lives. After 11 years we have become quite popular among (not only) European demographers, and many of them are returning to our conference each year. 

We encourage everyone to try new things; we love unorthodox ways of presenting the research, and most importantly, we support fun. Because demography is fun. 


***
#### The **11.5^th^ Conference of Young demographers** is going online!####
#### You can find the **Programme**  [**here**](https://drive.google.com/file/d/1tSGiEx4osU3XkSCl7A0fyI5W5mLcT3ZH/view?usp=sharing).####
Please note that the programme is subject to change. 

***
After giving it careful consideration, we have decidied to postpone the 12^th^ year of our conference for summer (exact date TBA in January). We wish for nothing more than meeting you all in person here in Prague and we believe a) the situatin will get better (fingers crossed) and b) Prague in summer is way more fun than Prague in winter!

However, we know, that many of you have applied for an event in February so we have decided to organize a smalle online conference-like event in the days of originally planned conference which is from **3^rd^ to 5^th^ February 2021** (Wednesday to Friday). The number of presenters will be limited as well as the time for presenting, so we do not overwhelm you by yet another Zoom event.

The call for papers is now closed. We will looking forward to you submitting for the **13^th^ Conference of Young Demographers in 2022**!!

***
#### The **12th Conference of Young Demographers** is unfortunatelly going online again!####
#### You can find the **Programme**  [**here**](https://docs.google.com/document/d/1uN3iWEE0ZihcutTo9AxZHCJOpPKDLxO-rwMP1KcGVBQ/edit?usp=sharing).####
***
We will meet in the virtual environment of [Gather Town](https://gather.town/) on **23^rd^ to 25^th^ June 2021** (Wednesday to Friday). Every participant will get 3 minutes to present his work in flash presentation followed by a 60 minute poster session. 

Attendees/presenters can find more information in their emails. 

We are super happy to announce that **Dr Mariona Lozano Riera** ([twitter](https://twitter.com/marionleitz)), **Dr José Manuel Aburto** ([twitter](https://twitter.com/jm_aburto)) and **Dr Ilya Kashnitsky** ([twitter](https://twitter.com/ikashnitsky)) will join us to talk about their journey through academia. 


The call for papers is now closed. We will looking forward to you submitting for the **13^th^ Conference of Young Demographers in 2022**!!


In case you have any questions about conference please do not hesitate to contact us!