   ***
   
# 0. ročník konference "Napříč": 5. prosince 2020  
A již přihlášené příspěvky aneb na koho a co se můžete těšit...    

 * Tereza nás upozorní na **Přehlížené mikrobiomy**: *Ze všech tělních mikrobiomů se neustále skloňuje ten střevní, ale co ty ostatní? Nechte se přesvědčit o tom, že třeba orální nebo vaginální mikrobiom nezůstávají - co se týče zajímavostí - za střevním mikrobiomem nikterak pozadu!*  
 * Jan a jeho **Komentovaná procházka vybranými myšími orgány**: *Podejte mi ruku a nechte se vést...  Light sheet fluorescenční mikroskopie v kombinaci s metodami projasňování tkání nám umožňují 3D zobrazování celých orgánů a ještě mnohem více!*  
 * Iva a její příspěvek **O nejnebezpečnějších a zároveň nejúžasnějších tvorech naší planety**: *Víte, jaké zvíře na planetě zemi je nejvíc nebezpečné a způsobuje nejvíce lidských úmrtí? A které je zároveň úžasné a fascinující? Přijďte a nechte se překvapit :-)*  
 * Ivana nám nabídne **Objetí: recept proti stárnutí**: *Jedná se o téma multidisciplinární zasahující do oborů nejen přírodních a lékařských věd, ale také např. do psychologie a non-verbální komunikace. Příspěvek bude převážně zaměřen na zdravotní přínosy objímaní, ale zmíněny budou i tipy a techniky správného objetí. *  
 * Radek nám něco poví **O původu zdrojů organických aerosolů v ovzduší ČR**: *Víte co to jsou atmosférické aerosoly a jakými procesy vznikají? Myslíte si že nevíte? Tak se pojďme společně přesvědčit o tom, že ty aerosoly i jejich zdroje, všichni moc dobře známe!*  
 * Milada nám dá možnost volby **Kontakt se stonožkou, stav beztíže ve vesmírné lodi nebo infarkt?**: *Všichni jednou zaklepem na nebeskou bránu! Důvody jsou však různé, některé časté, jiné originální. Kdy splyneš s davem (zemřelých) a kdy budeš jedinečná (mrtvola)? Exkurz do analýzy příčin smrti.*  
 * S Hankou nás čeká **Výuka matematiky on-line**: *Zkušenosti z on-line výukou matematiky na naší fakultě.*  
 * Petra snad dorazí na konferenci a neřekne nám **A já na ni zapomněl jako na smrt!**: *Smrt - co to vlastně je? Opravdu se týká těch druhých a nás ne?Co nám již podle starých filosofů myšlenka na smrt dává a co bere?*  
 * Irena nám poradí **Jak zaujmout nadprůměrné, průměrné i podprůměrné zároveň?**: *Různé typy studentů si žádají různé přístupy. Jak vyhovět všem během jedné vyučovací jednotky? Příklady motivačních nástrojů.*  
 * Eva nám poví příběh **Želvuška šla na vandr**: *Je život v polárních ledovcových ekosystémech limitován opravdu mrazem? Jak dlouhé cesty jsou schopni zvládat tamní vrcholoví predátoři? Jak často cestují a jak?*  
  * Carlos na nás bude apelovat s příspěvkem **Interdisciplinarita jako základ efektivního řešení problematiky sexuálně přenosných infekcí**: *Problematika sexuálně přenosných infekcí (STIs) představuje i v dnešní společnosti poměrně tabuizované a citlivé téma z čehož vyplývají i komplikace při jejím řešení. Problematika STIs výrazně přesahuje rámec infektologie a venerologie, zasahuje do oblasti sexuologie, sociologie, psychologie, dalších lékařských, ale i nelékařských vědních disciplín. Pro komplexní uchopení této problematiky je tedy inherentní přistupovat k tématu s notnou dávkou interdisciplinarity.*
  * Honza nás nakrmí svými vědomostmi **Kdy se brambor rozhodne tvořit brambor?**:*Tvorba hlíz je kontrolována několikery procesy. Proč je důležitý list? A co na to sacharóza?*
  * Vlasta představí krtky **Morfometrická analýza pažní kosti u krtků**:*Rod Talpa se v Evropě vyznačuje vysokou mírou endemity. Pomocí morfometrické analýzy z fosilních nálezů pažní kosti krtkovitých jsme zjistili, že většina humerální charakteristiky odpovídají proporcím malých forem z období raného pleistocénu, které jsou tradičně interpretovány jako samostatný druh Talpa minor (Freudenberg, 1914). Ve srovnání s nedávnými druhy, výrazně robustnějšími fenotypy popsanými jako Talpa europaea magna (Wondřich, 1893), je humer menší formy Talpa obecně štíhlejší, tuberculum teres je menší, zatímco caput humeri je širší v distální části.*
  
 **A S ČÍM PŘIJDEŠ TY?**

