---
pagetitle: Napříč
---

<link rel="stylesheet" href="styles.css" type="text/css">

*As Young Demographers we also do some other activities for the people from our Faculty of Science. The rest of this page is therefore mainly for them.*

## Konference "Napříč"
Úplně na úvod musíme vyzdvihnout zásluhy Heleny Ferklové. Domníváme se, že nebýt jí, tak by spousta z nás nikdy skutečně nepochopila kolik úžasných lidí dělá neuvěřitelně mnoho zajímavých věcí napříč katedrami, sekcemi a celou fakultou. Jsme hrdými přírodovědci a toužíme potom setkávat se s ostaními hrdými přirodovědci.  

Za tímto účelem, v době intenzivního sociální distancu, ordinujeme sociální blízkost!  

Hlavním cílem našich konferencí (doufáme, že pravidelných), je seznámit se vzájemně s našimi odbornými zájmy. Inspirovat se a s trochou štěstí navázat i mezioborovou spolupráci.  

***
### 0. ročník konference "Napříč" aneb _"kdo může ten přijde, kdo nemůže přijde příště"_
20 (?) příspěvků. Dokonale připravených. Pouhé 3 minuty monologu jedné osoby a pak mnoho minut inspirativní diskuze ve větším i menším kolektivu.  

<span style="color:navy">**ROZHODNUTO: PES je mrtev a my už nechceme nic odkládat, proto jsme se rozhodly pro spontánní akci a jak již podnázev našeho nultého ročníku napovídá: _kdo může, ten přijde, kdo nemůže přijde příště!_**<span>

<span style="color:navy">**KDY: 24. července 2021 od 18:00**<span>

<span style="color:navy">**KDE: Amfiteátr na stráni mezi Albertovem a Viničnou** (v případě deště bude pankový přesun do budovy - nechte se překvapit kterou místností si budeme krýt záda)<span>

Chcete-li se stále zúčastnit (**i pasivně!**), pak se prosím **registrujte [zde](https://docs.google.com/forms/d/e/1FAIpQLSdTsXRg_oz63GNAZrjUz5EtYo4Bh3nVM2qwyqpcmdGBadsJtA/viewform?usp=pp_url)** Téma můžete ponechat stejné (třeba je jen zkopírovat z [našich stránek](https://youngdemographers.github.io/napric0-prispevky), ale můžete zvolit i jiné.

Vše ostatní zůstává stejné a doufáme, že se potkáme s co nejvíce přírodovědci!

Slibujeme, že se v zimním semestru pokusíme uspořádat 1. ročník/semestřník a dát prostor vám všem, kteří si v létě užíváte dovolených a jiných kratochvílí!

***

Už se nemůžete dočkat? My také ne... a jsme velice šťastné, že již máme [třináct přihlášených příspěvků](https://youngdemographers.github.io/napric0-prispevky)!

Více si přečtěte [zde](https://drive.google.com/file/d/1T7jNMGQ6CsX1BiomOitX1GN95Y3m0or4/view?usp=sharing).  
Přihlaste se [zde](https://docs.google.com/forms/d/e/1FAIpQLScmNP5Q-oHEjIB3rXSIjVWdWfxEXyUg0Fz0Pa8tvnqDzA0i8Q/viewform).  
Chcete-li mít přehled nezapomeňte se zapsat na náš [mail list](https://docs.google.com/forms/d/e/1FAIpQLSetQ4e3fc4qpA-GR1qt7GNC6dxPjhEN3Xbbz9yuXf312E_RgQ/viewform)

***

**Upozornění:**
Přestože jsme přesvědčené o tom, že konference "Napříč" je velkým přínosem nejen naší fakultní akademické obci, ale i celému vědeckému světu, ráday bychom upozornily, že ji nelze zaměnit s oficiálními vědeckými aktivitami, které jsou po studentech a pracovnících požadovány (např. za účast na odborných konferencích atp.). Budeme však rády, pokud ji i tak budete vnímat jako příležitost pro osobní rozvoj a třeba ji zmíníte jako extrakurikulární aktivitu v ISP a příbuzných výkazech.

***

V případě dlouhé chvíle si můžete prohlédnout (již neplatný) příspěvek v magazínu [Přírodovědci.cz](https://www.prirodovedci.cz/templates/modules/magazin/mobile/web/viewer.php?hash=MzMxL3ByaXJvZG92ZWRjaS0yMDIwLTA0LXdlYi0wMS5wZGY=). Nebo si raději přečíst rozhovor s panem děkanem nebo nějaký pěkný článek o kamení. 


My se na vás všechny těšíme a posíláme pusinku (sněhovou).

**Milostné dopisy v elektronické podobě nám dál pište na:**  
*jitka.slaba at natur.cuni.cz*
*anna.altova at natur.cuni.cz* 